In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../data/course.csv")
df.head()

                 course_name     skill         level   career_path
0      SQL for Data Analysis       SQL      Beginner  Data Analyst
1       Advanced SQL Queries       SQL  Intermediate  Data Analyst
2      Power BI Fundamentals  Power BI      Beginner  Data Analyst
3  Power BI Dashboard Design  Power BI  Intermediate  Data Analyst
4    Excel for Data Analysis     Excel      Beginner  Data Analyst

In [3]:
df.shape

(28, 4)

In [4]:
df['career_path'].value_counts()

career_path
Data Analyst                 7
Data Scientist               7
Software Developer           6
Machine Learning Engineer    5
Business Analyst             3
Name: count, dtype: int64

In [5]:
df['combined']=(df['career_path']+" "+ df['skill']+" "+df['level'])

In [6]:
df[["course_name","combined"]].head()

                 course_name                            combined
0      SQL for Data Analysis           Data Analyst SQL Beginner
1       Advanced SQL Queries       Data Analyst SQL Intermediate
2      Power BI Fundamentals      Data Analyst Power BI Beginner
3  Power BI Dashboard Design  Data Analyst Power BI Intermediate
4    Excel for Data Analysis         Data Analyst Excel Beginner

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

tfidf_matrix = tfidf.fit_transform(df["combined"])

print(tfidf_matrix.shape)

(28, 33)

In [8]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(tfidf_matrix)

similarity.shape

(28, 28)

# TF-IDF 
text->numbers
# cosine similarity
numbers->similarity score

In [9]:
def recommend_courses(career_goal):

    matches = df[df["career_path"] == career_goal]

    return matches[["course_name","skill","level"]]

In [10]:
recommend_courses("Data Analyst")

                 course_name       skill         level
0      SQL for Data Analysis         SQL      Beginner
1       Advanced SQL Queries         SQL  Intermediate
2      Power BI Fundamentals    Power BI      Beginner
3  Power BI Dashboard Design    Power BI  Intermediate
4    Excel for Data Analysis       Excel      Beginner
5      Statistics Essentials  Statistics      Beginner
6   Python for Data Analysis      Python  Intermediate

In [11]:
career_skills = {
    "Data Analyst": ["SQL", "Power BI", "Excel", "Statistics", "Python"],
    "Data Scientist": ["Python", "Statistics", "Machine Learning", "Deep Learning"],
    "Software Developer": ["Java", "DSA", "OOP", "Web Development"],
    "Machine Learning Engineer": ["Python", "Machine Learning", "MLOps", "Docker"],
    "Business Analyst": ["Business Analysis", "Agile"]
}

In [12]:
def find_skill_gaps(career_goal, known_skills):

    required_skills = career_skills[career_goal]

    missing_skills = []

    for skill in required_skills:
        if skill not in known_skills:
            missing_skills.append(skill)

    return missing_skills

In [13]:
find_skill_gaps(
    "Data Analyst",
    ["Python", "Excel"]
)

['SQL', 'Power BI', 'Statistics']

In [14]:
def recommend_by_skill_gap(career_goal, known_skills):

    gaps = find_skill_gaps(career_goal, known_skills)

    recommendations = df[
        (df["career_path"] == career_goal) &
        (df["skill"].isin(gaps))
    ]

    return recommendations[
        ["course_name", "skill", "level"]
    ]

In [15]:
recommend_by_skill_gap(
    "Data Analyst",
    ["Python", "Excel"]
)

                 course_name       skill         level
0      SQL for Data Analysis         SQL      Beginner
1       Advanced SQL Queries         SQL  Intermediate
2      Power BI Fundamentals    Power BI      Beginner
3  Power BI Dashboard Design    Power BI  Intermediate
5      Statistics Essentials  Statistics      Beginner

In [16]:
level_order = {
    "Beginner": 1,
    "Intermediate": 2,
    "Advanced": 3
}

In [17]:
def generate_roadmap(career_goal, known_skills):
    recommendations = recommend_by_skill_gap(
        career_goal,
        known_skills
    ).copy()
    recommendations["level_rank"] = recommendations["level"].map(level_order)
    roadmap = recommendations.sort_values("level_rank")
    return roadmap[["course_name", "skill", "level"]]

In [18]:
generate_roadmap(
    "Data Analyst",
    ["Python", "Excel"]
)

                 course_name       skill         level
0      SQL for Data Analysis         SQL      Beginner
2      Power BI Fundamentals    Power BI      Beginner
5      Statistics Essentials  Statistics      Beginner
1       Advanced SQL Queries         SQL  Intermediate
3  Power BI Dashboard Design    Power BI  Intermediate

In [4]:
print(generate_roadmap.column)

NameError: name 'generate_roadmap' is not defined

In [5]:
print(df.columns)

Index(['course_name', 'skill', 'level', 'career_path'], dtype='object')

In [19]:
result=generate_roadmap()

TypeError: generate_roadmap() missing 2 required positional arguments: 'career_goal' and 'known_skills'

In [20]:
result = generate_roadmap()

print(result.columns)

TypeError: generate_roadmap() missing 2 required positional arguments: 'career_goal' and 'known_skills'

In [21]:
generate_roadmap.head()

AttributeError: 'function' object has no attribute 'head'